### ISSUE TITLE
different Token Accuracy on same sets

### ISSUE THREAD

**Issue by NewEricWang** [yajiemiao/eesen#16]
I am trying to train RNN model for handwriting char actor string recognition  by eesen tool. I use training set as cv set. In other words, My cv set is same as training set. But I find Token Accuracy of training set  is different with one of cv set at each epoch  in training log. 
Some log is as following: 
EPOCH 4 RUNNING ... ENDS [2016-Jul-12 16:15:11]: lrate 0.000245, TRAIN ACCURACY 55.2512%, VALID ACCURACY 78.5178%

**Comment by yajiemiao** [comment]
This is normal because the training accuracy is a summary of the whole training epoch, in which the training accuracy gradually improves from the beginning towards the end of the epoch. In comparison, the valid accuracy is from the model obtained at the end of the training epoch. 

As training progresses, the train accuracy will catch up and eventually surpass the valid accuracy.

**Comment by NewEricWang** [comment]
Thanks a lot!
